### ISSUE TITLE
買い物リスト

### ISSUE THREAD

**Issue by takeyari** [takeyari/takeyari#1]
優先度順で
1. - [ x] 女装衣装
1. - [ ] ワンフェスのカタログ
1. - [ ] PS4用のハンコン
1. - [ ] GTSport(未発売)
1. - [ ] Xbox360
1. - [ ] ケイブシューティングコレクション
1. - [ ] x220のドッキングステーション
1. - [ ] MacBookPro

**Comment by rokoucha** [comment]
チェックボックスを使え

**Comment by rinsuki** [comment]
そうだよ

**Comment by takeyari** [comment]
多分数年は埋まらないので不要

**Comment by rokoucha** [comment]
埋まらない、じゃあないんだよ
埋めていこうな

**Comment by rinsuki** [comment]
そうだよ
